/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-11-25 10:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import product.vo.*;

public final class pdt_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/page/product/../../include/footer.jsp", Long.valueOf(1637830442655L));
    _jspx_dependants.put("/page/product/../../include/header.jsp", Long.valueOf(1637836808825L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("product.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

ArrayList<ProductInfo> pdtList = (ArrayList<ProductInfo>)request.getAttribute("pdtList");
ArrayList<PdtCata> cataList = (ArrayList<PdtCata>)request.getAttribute("cataList");

PdtPageInfo pdtPageInfo = (PdtPageInfo)request.getAttribute("pdtPageInfo");

String args ="", schargs = "";
// 검색관련 쿼리스트링 
if(pdtPageInfo.getKeyword() != null && !pdtPageInfo.getKeyword().equals(""))	
	schargs += "&keyword=" + pdtPageInfo.getKeyword();
if(pdtPageInfo.getCata() != null && !pdtPageInfo.getCata().equals(""))
	schargs += "&cata=" + pdtPageInfo.getCata();
if(pdtPageInfo.getSprice() != null && !pdtPageInfo.getSprice().equals(""))
	schargs += "&sprice=" + pdtPageInfo.getSprice();
if(pdtPageInfo.getEprice() != null && !pdtPageInfo.getEprice().equals(""))
	schargs += "&eprice=" + pdtPageInfo.getEprice();

args = "?cpage=" + pdtPageInfo.getCpage() + schargs;
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/reset.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainSlide.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainLayout.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/base.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/footer.css\" />\r\n");
      out.write("\t<script src=\"js/jquery-3.6.0.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/mainSlide.js\"></script>\r\n");
      out.write("\t<script src=\"js/mainPage_scroll.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".maindiv{\r\n");
      out.write("\theight: 3000px;\twidth:1200px; margin: 0 auto;\r\n");
      out.write("\tbackground-color:#d3d3d3;\r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write(".pdt_contents {\r\n");
      out.write("\twidth:1200px;  margin: 0 auto;\r\n");
      out.write("\r\n");
      out.write("\toverflow:hidden;\r\n");
      out.write("\theight:100%;\t\r\n");
      out.write("\t\r\n");
      out.write("\tpadding-bottom:300px;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".pdt { margin:20px; border:1px black solid; float:left; font-size:1.4em; }\r\n");
      out.write("\r\n");
      out.write(".pdt_price { text-decoration:line-through; color:gray; font-size:0.9em; }\r\n");
      out.write("\r\n");
      out.write(".pdt_real_price { color:red; font-size:1.2em; }\r\n");
      out.write("\r\n");
      out.write(".page_wrapper {\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tleft:0%; bottom:5%;\r\n");
      out.write("\ttransform:translate(0%, -5%); \r\n");
      out.write("\twidth: 1200px; height: 60px; \r\n");
      out.write("\tpadding-top:50px;\r\n");
      out.write("\tpadding-bottom:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tpadding-bottom:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("<!-- #header 영역 시작 -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div id=\"logo\"><h1 class=\"logo\"><a href=\"mainPage.jsp\"><img src=\"img/logo.png\" alt=\"로고\" class=\"logo\" /></a></h1></div>\r\n");
      out.write("\t<ul id=\"infoMenu\">\r\n");
      out.write("\t\t<li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("\t\t<li><a href=\"login_form.jsp\">로그인</a></li>\r\n");
      out.write("\t\t<li><a href=\"login_form.jsp?url=page/order/cart_list.ord\">장바구니</a></li>\r\n");
      out.write("\t\t<li><a href=\"page/member/update_form.jsp\">정보수정</a></li>\r\n");
      out.write("\t\t<li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t<li><a href=\"cart_list.ord\">장바구니</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<h2>검색 창</h2>\r\n");
      out.write("\t<ul id=\"searchMain\">\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<select class=\"hand\" id=\"search_kind\">\r\n");
      out.write("\t\t\t\t<option value=\"전체\">전체</option>\r\n");
      out.write("\t\t\t\t<option value=\"가위\">가위</option> \r\n");
      out.write("\t\t\t\t<option value=\"문구\">문구</option>\r\n");
      out.write("\t\t\t\t<option value=\"주방\">주방</option>\r\n");
      out.write("\t\t\t\t<option value=\"etc\">etc</option>\r\n");
      out.write("\t\t\t\t<option value=\"도전펀딩\">도전펀딩</option>\r\n");
      out.write("\t\t\t\t<option value=\"펀딩하기\">펀딩하기</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><input type=\"text\"  id=\"search_bar\" /></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"img/search_btn.png\" id=\"search_img\" alt=\"검색\" /></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<h2>메인 메뉴</h2>\r\n");
      out.write("\t<ul id=\"navigation\">\r\n");
      out.write("\t\t<li><a href=\"pdt_list.pdt\">가위</a></li>\r\n");
      out.write("\t\t<li><a href=\"page/product/pdt_office.jsp\">문구</a></li>\r\n");
      out.write("\t\t<li><a href=\"page/product/pdt_kitchen.jsp\">주방</a></li>\r\n");
      out.write("\t\t<li><a href=\"page/product/pdt_etc.jsp\">etc</a></li>\r\n");
      out.write("\t\t<li><a href=\"chal_list.chal\">도전펀딩</a></li>\r\n");
      out.write("\t\t<li><a href=\"pdt_list.fdg\">펀딩하기</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<h2>SNS</h2>\r\n");
      out.write("\t<ul id=\"sns\">\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"img/instagram.png\" alt=\"인스타\" /></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"img/facebook.jpg\" alt=\"페이스북\" /></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"img/twitter.png\" alt=\"트위터\" /></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- div#header 영역 종료 -->\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<!-- ------------------------------------------------------------------------------------------------ -->\r\n");
      out.write("<div class=\"pdt_contents\" >\r\n");
      out.write("<br />\r\n");
      out.write("<h2 align=\"center\">mvc 테스트용 </h2>\r\n");
      out.write("<br />\r\n");
      out.write("<p align=\"right\" style=\"padding:15px 75px 15px; \"> 인기 | 판매량 | 높은가격| 낮은가격 </p>\r\n");

if(pdtList.size() > 0){
// 상품 검색결과가 있으면
	for(int i=0;i<pdtList.size(); i++){
		ProductInfo pi = pdtList.get(i);
		String lnk = null;
		if(pi.getPi_stock() != 0){		// 상품의 재고가 남아있는 경우... 무제한이 -1
			lnk = "<a href=\"pdt_view.pdt" + args + "&piid=" + pi.getPi_id() + "&sort=" + pdtPageInfo.getSort() +
					"&psize=" +pdtPageInfo.getPsize() + "\">";
		}else{		// 상품의 재고가 없는 품절일 경우
			lnk = "<a href=\"javascript:alert('품절된 상품입니다.');\">";
		}
		
		if(pdtPageInfo.getPsize() == 12) {
		// 한 페이지에 12개의 상품 목록을 보여줄 경우(한 줄에 3	개씩 보여줌)
			if(i%3 == 0)		out.println("<div align='center'>");

      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t");
      out.print(lnk );
      out.write("<img src=\"page/product/img/");
      out.print(pi.getPi_img1() );
      out.write("\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t");
      out.print(pi.getPi_name() );
      out.write("</a><br /><span class=\"pdt_price\">");
      out.print(pi.getPi_price() );
      out.write(" 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ");
      out.print((int)(pi.getPi_price() * (1-pi.getPi_discount()))  );
      out.write(" 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

			if(i%4 == 3) 	out.println("</div>");
		}
	}

}else{
	out.println("<div>검색된 상품이 없습니다.</div>");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 예제 데이터 시작 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pdt\">\r\n");
      out.write("\t<a href=\"pdt_view.pdt?cpage=1&piid=a103&sort=idd&psize=12\"><img src=\"page/product/img/a103_info_1.jpg\" style=\"width:350px; height:350px; padding-bottom:25px;\" /><br />\r\n");
      out.write("\t아이용 왼손잡이용 가위</a><br /><span class=\"pdt_price\">3000 원</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1800 원\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 예제 데이터 끝 -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

if (pdtList.size() > 0){
// 상품 검색결과가 있으면 페이지 번호를 출력
	out.println("<div class='page_wrapper'>");
	out.println("<p style='font-size:1.25em; width:100%;' align='center'>");

	args = "?sort=" + pdtPageInfo.getSort() + "&psize=" + pdtPageInfo.getPsize() + schargs;
	
		if(pdtPageInfo.getCpage() == 1){				
			out.println("[&lt;&lt;]&nbsp;&nbsp;[&lt;]&nbsp;&nbsp;");
		}else{
			out.print("<a href='pdt_list.pdt" + args + "&cpage=1'>[&lt;&lt;]</a>&nbsp;&nbsp;");
			out.println("<a href='pdt_list.pdt" + args + "&cpage=" + (pdtPageInfo.getCpage() - 1) + "'>[&lt;]</a>&nbsp;&nbsp;");
		}
		
		for(int i=1, j=pdtPageInfo.getSpage(); i<= pdtPageInfo.getBsize() && j <= pdtPageInfo.getEpage(); i++, j++){
		// i : 루프 돌릴 횟수 검사하는 용도의 변수, j : 페이지 번호 출력용 변수
			if(pdtPageInfo.getCpage() == j){
				out.print("&nbsp;<strong>" + j + "</strong>&nbsp;");
			}else{
				out.print("&nbsp;<a href='pdt_list.pdt" +args + "&cpage=" +j + "'>" + j + "</a>&nbsp;");
			}
		}
		
		
		if(pdtPageInfo.getCpage() == pdtPageInfo.getPcnt()){
			out.println("&nbsp;&nbsp;[&gt;]&nbsp;&nbsp;[&gt;&gt;]");
		}else{
			out.print("&nbsp;&nbsp;<a href='pdt_list.pdt" + args + "&cpage=" + (pdtPageInfo.getCpage() + 1 ) + "'>[&gt;]</a>");
			out.println("&nbsp;&nbsp;<a href='pdt_list.pdt" +args + "&cpage=" + (pdtPageInfo.getPcnt()) + "'>[&gt;&gt;]</a>");
		}

	out.println("</p>");
	out.println("</div>");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ------------------------------------------------------------------------------------------------ -->\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t<!-- footerInner영역 시작 -->\r\n");
      out.write("\t<div class=\"footerInner\">\r\n");
      out.write("\t\t<div class=\"corp_area\">\r\n");
      out.write("\t\t\t<ul class=\"corp_list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">이용 약관</a></li> |\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">개인정보 처리방침</a></li> |\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"company_info_area\">\r\n");
      out.write("\t\t<img src=\"img/logo_long.png\" width=\"191px\" height=\"59px\" alt=\"Logo\" class=\"footerLogo\"/>\r\n");
      out.write("\t\t\t<div class=\"ci_area\">\r\n");
      out.write("\t\t\t\t<ul class=\"company_info\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">회사명</a></li> |\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">대표이사</a></li> |\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">회사 주소</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ci_area\">\r\n");
      out.write("\t\t\t<ul class=\"company_info\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">사업자 등록번호</a></li> |\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">사업자 정보</a></li> |\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">고객센터 전화번호</a></li> |\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">회사 이메일</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
